### ISSUE TITLE
Error git

### ISSUE THREAD

**Issue by sebastienserre** [Weysan/docker-php7.0#1]
Hello
I'm trying to use your repo to make my dev environement and on a docker-compose up I've:
`Step 9 : RUN git clone --branch php7 https://github.com/php-memcached-dev/php-memcached /usr/src/php/ext/memcached   && cd /usr/src/php/ext/memcached   && docker-php-ext-configure memcached   && docker-php-ext-install memcached
 ---> Running in 971f0923e4ea
/bin/sh: 1: git: not found
ERROR: Service 'web' failed to build: The command '/bin/sh -c git clone --branch php7 https://github.com/php-memcached-dev/php-memcached /usr/src/php/ext/memcached   && cd /usr/src/php/ext/memcached   && docker-php-ext-configure memcached   && docker-php-ext-install memcached' returned a non-zero code: 127
`
Any idea to solve please?

**Comment by Weysan** [comment]
Yes, I forgot to put a line in order to install git in the PHP dockerfile. i will fix it quickly until tomorrow, I will let you know as soon as it's fix!

**Comment by sebastienserre** [comment]
Great many thx

**Comment by Weysan** [comment]
I've just pushed a new dockerfile to fix the problem. Can you try with the new commit ? thanks!

**Comment by Weysan** [comment]
Is the fix working @sebastienserre ?

**Comment by sebastienserre** [comment]
Sorry, just tested, yes it fixed
